version: "2"

services:
  yunpan:
    image: ghcr.io/dreamhunter2333/yunpan:latest
    container_name: yunpan
    environment:
      - root_path=/data
      - password=admin
      - secret=admin
    volumes:
      - ../data:/data
    ports:
      - "8000:8000"
