name: Docker Image Release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - uses: actions/checkout@v2

      - name: Install and Build
        run: cd front && yarn && yarn build && rm -rf node_modules

      - name: Docker Login
        uses: docker/login-action@v1.8.0
        with:
          registry: registry.cn-beijing.aliyuncs.com
          username: ${{ secrets.ALIYUN_REGISTRY_USERNAME }}
          password: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}

      - name: Build the Docker image
        run: docker build . --file docker/Dockerfile --tag registry.cn-beijing.aliyuncs.com/dreamhunter/yunpan:${{ steps.get_version.outputs.VERSION }}
      - name: Push the Docker image
        run: docker push registry.cn-beijing.aliyuncs.com/dreamhunter/yunpan:${{ steps.get_version.outputs.VERSION }}
